# Generated by Django 5.1.7 on 2025-03-15 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                ("brandId", models.IntegerField(primary_key=True, serialize=False)),
                ("brandName", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ComponentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="MainGroup",
            fields=[
                ("mainGroup", models.IntegerField(primary_key=True, serialize=False)),
                ("mainGroupName", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Spec",
            fields=[
                ("specId", models.IntegerField(primary_key=True, serialize=False)),
                ("spec", models.CharField(max_length=100)),
                ("mainSpec", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SpecValue",
            fields=[
                ("valueId", models.IntegerField(primary_key=True, serialize=False)),
                ("value", models.CharField(max_length=100)),
                ("trailer", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CompatibilityRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("relationType", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=100)),
                (
                    "componentType1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_rules",
                        to="builder.componenttype",
                    ),
                ),
                (
                    "componentType2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_rules",
                        to="builder.componenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("sku", models.BigIntegerField(primary_key=True, serialize=False)),
                ("productName", models.CharField(max_length=255)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="builder.brand"
                    ),
                ),
                (
                    "componentType",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="builder.componenttype",
                    ),
                ),
                (
                    "mainGroup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="builder.maingroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductSpec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="builder.product",
                    ),
                ),
                (
                    "spec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="builder.spec"
                    ),
                ),
                (
                    "value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="builder.specvalue",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubGroup",
            fields=[
                ("subGroup", models.IntegerField(primary_key=True, serialize=False)),
                ("subGroupName", models.CharField(max_length=100)),
                (
                    "mainGroup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="builder.maingroup",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="subGroup",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="builder.subgroup"
            ),
        ),
    ]
