# Generated by Django 5.1.7 on 2025-03-15 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compatibilityrule",
            name="componentType1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="source_rules",
                to="builder.maingroup",
            ),
        ),
        migrations.AlterField(
            model_name="compatibilityrule",
            name="componentType2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="target_rules",
                to="builder.maingroup",
            ),
        ),
        migrations.RemoveField(
            model_name="product",
            name="componentType",
        ),
        migrations.DeleteModel(
            name="ComponentType",
        ),
    ]
